apiVersion: apps/v1
kind: Deployment
metadata:
  name: logi-gniazdka
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: logi-gniazdka
  template:
    metadata:
      labels:
        app: logi-gniazdka
    spec:
      containers:
        - name: logi-gniazdka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $val := .Values.config }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}